---

- name: Setup federated auth in keystone vhost
  template:
    src: keystone-vhost.conf.j2
    dest: "{{ keystone.vhost_path }}"
    backup: yes
  notify: restart apache
  
- name: Configure federated auth in keystone - auth section
  ini_file:
    dest: "{{ keystone.conf_path }}"
    section: auth
    option: methods
    value: external,password,token,oauth1,saml2
    backup: yes
  notify: restart apache
  
- name: Configure federated auth in keystone - saml2 section
  ini_file:
    dest: "{{ keystone.conf_path }}"
    section: saml2
    option: remote_id_attribute
    value: 'Shib-Identity_provider'
    backup: yes
  notify: restart apache
  
- name: Configure federated auth in keystone - federation section opt2
  ini_file:
    dest: "{{ keystone.conf_path }}"
    section: federation
    option: trusted_dashboard
    value: "{{ keystone.trusted_dashboard }}"
    backup: yes
  notify: restart apache
